name: Deploy Next.js to S3

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ca-central-1
  S3_BUCKET: shaikh-portfolio-site
  CLOUDFRONT_DISTRIBUTION_ID: E13Q3LKV517H9V

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build (static export)
        run: |
          npm run build
          # test -d out || (echo "❌ Next.js export folder ./out not found" && exit 1)

      - name: Deploy on Heroku
        uses: 5hojib/heroku-deploy-action@v1.2.10
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
     
